services:
  - type: web
    name: slack-change-request-bot
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SLACK_BOT_TOKEN
        value: YOUR_SLACK_BOT_TOKEN
      - key: SLACK_SIGNING_SECRET
        value: YOUR_SLACK_SIGNING_SECRET
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: |
          {
            "type": "service_account",
            "project_id": "es-request-bot",
            "private_key_id": "e0b7c2c2877d90539283a04a4f4553f9c8660dc9",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDlwEtbyfzKGV5f\neZ9FSF7n201mTBBiEagjGs+iSDK9uhkyqdjLcvpYEl6AK+WTTkEfImWf3T6qVunF\nGmBgzSKuBpSX9Rrn/b8Fgq/YECHtCbfbiqdeYyBBXFc716jRk1UZNBIY0/Scb6o+\nF+xPYBai7lUuQ64L06WFQevDk2tUyJvIlRdEUsQEALFoz8yT6ipX02rCj8CuFJA4\n3vVjP6WMK08dM91VD+ljNr51rH7gb802GlCNAHV7Vg8NfQihufHmHwbHHQiPkHcn\nnKWeUNaLYA2iq12m/KgFsbQ80dC7VOarmHUJ8lBT46dxelVaQCHVXO25KyGXO6SL\nI7bndohvAgMBAAECgf98LZ9oMcyfHE/SeH+KBO2wG8vE3lEAuN1ubvOsZ5DWT6E7\nkeYjEgIkk/rujOF7EqSDtbLZvBgU7O1XHATU17V1YPlQbHkMfE5W8VLNrKmBdNxJ\nKd39qDavWgDhE5DA6OanQw7uJRoDTO+7Q0ZKF7B/ymqjdwX9kwf3BBY9uAXGSQvN\n7rmoRuACYdOggoPABQ/OP0sL3k8HqgCgU7K1xKMBDnvVvZC7wlU8mjwD6y3GP/pt\nu/jhYOGqCCpd3fYyTP4sN03UVraevTeQ3clOjakSpaHPQncCekFVQsjr0oR6EP/J\nxlV2IZC5sOIhGFnsCYEG29G/n8aUvFiYcWIigAECgYEA9NRjql4Sn58urOU3tiFV\nm2fnMl0mvKSpcpbNWFOZ9N5Bg8P3W0/y0eDgchkO/2eAoZfabCqTRAQmtnleJv6O\nn559vs42J5xcyY39paLOMs3Hp9qWXLkue5J1/zpPVL0odRtgNVui+trNYLvuk0b5\nZv1SJy+V5lP3qZQzDCw/aG8CgYEA8DvJxwZ1j7uZ9Op6yIpp2mfzU/wxcc2vIZOE\nrrQ/ZAE1BxV/CuTXQOj5fUhe0u09fn1CRVCgYLNMw236OyWYB5P6wZPf+VaQAbPP\nD+IerqxJAd55YjfjPDjDj0AC33J7hOn0ekxsDnukoZvdIq5esY4Quw2fc9PkBIrp\nfEyK4AECgYEAwKnmqGoRM8W7oFldJxlCWeJBIPQHCMp3gfJEM+7OJ9FDMyLio9vd\nVOYnGgK4N6rGoeNzAk3ax9qQcGY//mWx7NB3WdDC8xbsObxgT5k3tOkU5fVxABTG\nDH5sFuZXCXM1xDo/0p2DOu82UZpymzluCGru3GFpD/Eh4zP5m+myGEcCgYEAnKwR\nYxhGUW/i70SAwQrsEAFdQvelc3fV8IrZrGpnMRxMbgtJ6FvoOi/2jgtFtD/+q+Ca\n+MOlZItq08WEvVA+Pyr2DYsYNe+LSWDv+IbaxcYccviZp0GVk+/dMi5n8TwjbEJ8\nK8ptamCetLsG1BhuL1Pce3Fd/VdCTOgfb+4nYAECgYBZsJQKcQTKVIEs9yx9QOKu\nkOUbKXY9Kl5Afqb1mvcZvdB2cYAbI+ekpvgOIHPGWr1LWoYgvlMEZ5En3+sJXWAi\nHFoLhXxKdr0bWlLY+U/AsTJj9HqCbzF2nVvjozM61rfrmQP6uUIv2DBu/TJvSxuo\nsU2wxwvjIOxubh9GY+3opw==\n-----END PRIVATE KEY-----\n",
            "client_email": "firebase-adminsdk-fbsvc@es-request-bot.iam.gserviceaccount.com",
            "client_id": "104479535272239978902",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40es-request-bot.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
